### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by liuyiji** [MiEcosystem/mijia_ble_standard#1]
https://github.com/MiEcosystem/mijia_ble_libs/tree/e534616616247e88c033112335a6362170e1d958
这个文档404呢

**Comment by TuChucheng** [comment]
mijia_ble_libs 是私有仓库 需要申请权限

**Comment by liuyiji** [comment]
方便告知一下从哪里申请么，有微信群还是qq或者邮箱之类的

**Comment by TuChucheng** [comment]
发邮件到miot-openhome@xiaomi.com 联系小米商务人员或产品经理
