### ISSUE TITLE
广播包的counter问题

### ISSUE THREAD

**Issue by JacyHuang** [MiEcosystem/mijia_ble_standard#2]
问题1：文档介绍"如果要广播不同的事件和属性，Frame Counter与Random Number合并成的Counter必须递增"
请问是如何组合，Random Number占3字节，Frame Counter占1字节，哪个是高位哪个是低位。

问题2：文档介绍”Frame Counter同一事件或属性至少重复10次，广播不同的事件和属性需要自增“
请问，我们做温湿度计的，温度变化或者湿度有变化，是否是每次都要自增？我们广播的内容会有温度、湿度和电量，就是三个事件。我们设置为每次轮流广播这三个事件，是否也是每次counter要自增。 同一事件或者属性至少重复10次。如果这期间，温度/湿度变化比较频繁，应该没办法保证到至少重复10次。

**Comment by TuChucheng** [comment]
你好，对于开发者不需要关注这些细节，直接调用接口 mibeacon_obj_enque 传入obj即可
